project:
  type: website
  output-dir: public

format:
  html:
    theme: cosmo
    link-external-newwindow: true # Apre automaticamente i link esterni/slide in nuove schede

lang: it

website:
  title: "Traiettorie consapevoli"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: glossario/cinematica.qmd
        text: Glossario Fisica
      - text: Lezioni 
        menu: 
          - href: presentazioni/Equazioni.qmd
            text: Equazioni di I grado
          - href: presentazioni/SezioneAurea.qmd
            text: Sezione aurea
      - text: Schemi
        menu:
          - href: schemi/Equa.qmd
            text: Equazioni di I grado

  # LA SIDEBAR DEVE ESSERE ALLINEATA A NAVBAR
  sidebar:
    id: glossario-sidebar
    title: "Argomenti Fisica"
    style: "docked"
    search: true
    contents:
      - section: "Fisica"
        contents:
          - href: glossario/cinematica.qmd
            text: "Cinematica"
          - href: glossario/accelerato.qmd
            text: Moto vario e MRUA  
          - href: glossario/virtlab.qmd
            text: Laboratori virtuali  

execute:
  echo: false    # Nasconde il codice in tutto il sito
  warning: false # Nasconde eventuali messaggi di errore tecnici

