project:
  type: website
  output-dir: public

format:
  html:
    theme: cosmo
    link-external-newwindow: true # Apre automaticamente i link esterni/slide in nuove schede

website:
  title: "Il mio Portale Didattico"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: glossario/cinematica.qmd
        text: Glossario Fisica
      - text: Lezioni 
        menu: 
          - href: presentazioni/Equazioni.qmd
            text: Equazioni di I grado
          - href: presentazioni/SezioneAurea.qmd
            text: Sezione aurea

  # LA SIDEBAR DEVE ESSERE ALLINEATA A NAVBAR
  sidebar:
    id: glossario-sidebar
    title: "Argomenti Fisica"
    style: "docked"
    search: true
    contents:
      - section: "Cinematica"
        contents:
          - href: glossario/cinematica.qmd
            text: "Cinematica"