---
title: "Equazioni di I grado"
format: html
---

## Risolvere un'equazione

Risolvere un'equazione di I grado significa trasformarlo nella forma normale
$$ax=b$$

Il primo passo è trasformare l'equazione iniziale in una somma di monomi (termini tipo $2x$, $3x^2$, 5, ...). 


Ma prima, si deve considerare le **parentesi ()**

## Prima di tutto, guarda dentro 🧐.  
Se contengono termini simili, si sommano algebricamente

Per esempio:
\begin{align*}
2x+(3x-5+1)=8x-5 \\
2x+(3x \overset{-5+1}{-4}) =8x-5
\end{align*}

prima si sommano  -5+1 nella parentesi



## Se prima c'è un ➕, oppure l'inizio e dopo 🫷🏼 $^*$
$^*$ c'è un +, un - o la fine del membro dell'equazione 

::: {layout="[[1, 1]]"}

:::{.callout-caution title="Come questi!"}
$$(2x+1)+...= ...$$
$$...+(3x-4) = ...$$
$$... = ...+(5x-1)$$
:::

::: {#Regolapiu}
Semplicemente si tolgono le parentesi

\begin{align*}
2x+\colorbox{yellow}{$(4x-1)$}&=\colorbox{yellow}{$(7x-5)$}-4 \\
3x+\colorbox{yellow}{$\not (4x-1 \not )$}&= \colorbox{yellow}{$\not(7x-5 \not$)}-4 \\  2x+4x-1&=7x-5-4
\end{align*}

:::
:::



## Se prima c'è un ➖  e dopo 🫷🏼$^*$ 
$^*$( c'è +, un - o la fine del membro dell'equazione)  

::: {layout="[[1, 1]]"}
::: {.callout-caution title="Come questi!"}
$$-(2x+1)-...= ...$$
$$...-(3x-4) = ...$$
$$... = ...-(5x-1)$$
:::

::: {#Regolameno}
si tolgono le parentesi, ma si riscrivono tutti i membri col segno cambiato

\begin{align*}
2x\colorbox{yellow}{$-($}4x-1\colorbox{yellow}{)}&=\colorbox{yellow}{$-($}7x-5\colorbox{yellow}{)}+4 \\
 2x\colorbox{yellow}{$-4x+1$}&=\colorbox{yellow}{$-7x+5$}+4 
\end{align*} 
:::
:::



## Se prima c'è un numero e dopo 🫷🏼 $^*$
$^*$ un +, un - o la fine del membro dell'equazione 

::: {layout="[[1, 1]]"}
::: {.callout-caution title="Come questi!"}
$$3(4x+1)+...= ...$$
$$...+5(3x-4) = ...$$
$$...+5(3x-4) = ...$$
$$... = ...-6(5x-1)$$
:::

::: {#Regolamonomio}
si tolgono le parentesi, si moltiplicano tutti i membri dentro la parentesi per il numero davanti

\begin{align*}
2x-3(2x-1)&=-4(2x-5)+4 \\ 
2x-3 {\color{lightgray}\cdot} (2x-1)&=-4(2x-5)+4 \\
2x\overset{-3 \cdot 2}{-6}x+\overset{-3 \cdot -1}{3}&=\overset{-4 \cdot 2}{-8}x+\overset{-4 \cdot -5}{20}+4
\end{align*}

::: {.callout-warning}
Il numero davanti va considerato **con il suo segno**!
:::

:::
:::

## Se ci sono due parentesi vicine
::: {layout="[[1, 1]]"}
::: {.callout-caution title="Come questi!"}
$$(4x+1)(2x+2)+...= ...$$
$$...+(2x-1(3x-4) = ...$$
$$... =(3x-4)(3x-4) ...$$
:::

:::{#Regolaparentesi}

si moltiplicano i membri a due a due, poi si semplifica e si toglie la parentesi come scritto sopra

\begin{align*}
6x^2-(3x-4)(2x-1)&= 0 \\ 
6x^2-(3x-4) {\color{lightgray}\cdot} (2x-1)&=0 \\
6x^2-(\overset{3x \cdot 2x}{6x^2}-\overset{3x \cdot -1}{3x} - \overset{-4 \cdot 2x}{8x}+\overset{-4 \cdot -1}{4}) &=0\\
6x^2-(6x^2 -11x+4) &=0\\
\cancel{6x^2}-\cancel{6x^2} +11x-4 &=0\\
\end{align*}

:::
:::

## Se dentro le due parentesi c'è la somma e la differenza degli stessi monomi

::: {layout="[[1, 1]]"}
::: {.callout-caution title="Come questi!"}
\begin{align*}
(2x-1)(2x+1)+ ...=...\\
... =...+ (4x-3)(4x+3) 
\end{align*}
:::

:::{#Regolasommadifferenza}
si applica il prodotto notevole
$$(A + B)(A - B) =A^2 - B^2$$
si scrive la differenza (-) dei quadrati dei due monomi

\begin{align*}
(3x-1)(3x+1)+2x &=9x^2+1\\
\overset{(3x)^2}{9x^2}-\overset{1^2}{1}+2x &=9x^2+1\\
\cancel{9x^2}-1+2x &=\cancel{9x^2}+1\\
\end{align*}

:::
:::

## Se la parentesi ha un quadrato

::: {layout="[[1, 1]]"}
::: {.callout-caution title="Come questi!"}
\begin{align*}
...+(2x-3)^2+ ...=...\\
... = (4x-3)^2+ ... 
\end{align*}
:::

:::{#Regolaquadrati}
si applica il prodotto notevole
$$(A \pm B)^2=A^2 \pm 2AB + B^2$$

\begin{align*}
(2x-3)^2-4x^2 &= -3\\
\overset{(2x)^2}{4x^2}-\overset{2 \cdot 2x \cdot -3}{12x}+\overset{3^2}{9}-4x^2 &=-3\\
\cancel{4x^2}-12x+9 -\cancel{4x^2}&=-3\\
\end{align*}
:::
:::


## 🏁 La fase finale: "Sposta e Risolvi"

Una volta eliminate tutte le parentesi e fatte le moltiplicazioni, ti troverai con una serie di monomi. Ora devi applicare la Regola del Trasporto.

1. Ordinare (Sinistra e Destra). Sposta tutti i termini con la $x$ a sinistra dell'uguale e tutti i numeri (termini noti) a destra.

::: {.callout-warning collapse="false"}

Attenzione: Quando un termine salta l'uguale, cambia segno!


$$2x \color{red}{-5} = \color{blue}{8x} + \color{black}4 \implies 2x \color{blue}{-8x} = 4 \color{red}{+5}$$

:::

---

2. Sommare (Riduzione). Somma i coefficienti delle $x$ tra loro e i numeri tra loro per arrivare alla forma:$$ax = b$$ 

---

3. Isolare la $x$. Per trovare il valore finale, dividi il numero a destra per il coefficiente della $x$:
$$x = \frac{b}{a}$$

---

::: {.callout-important collapse="false"}
💡 Un piccolo trucco per i calcoli
Quando arrivi alla forma $ax = b$, possono succedere tre cose:

|Risultato|Tipo |Esempio|
|--------------|------------|-------|
|Trovi un valore (es. $x = 2$)|Determinata|$3x = 6 \implies x = 2$|
|Ottieni $0x = 0$|Indeterminata|Hai infinite soluzioni|
|Ottieni $0x = 5$ (0 uguale a un numero)|Impossibile|Non esiste nessuna soluzione|
:Tipi di equazioni

:::




```{ojs}
//| output: false
// Funzione di utilità per disegnare un rettangolo standard
drawShape = (width, height, color) => {
  const ctx = DOM.context2d(200, 150);
  ctx.fillStyle = color;
  ctx.fillRect(10, 10, width, height);
  ctx.strokeStyle = "black";
  ctx.lineWidth = 2;
  ctx.strokeRect(10, 10, width, height);
  return ctx.canvas;
}
//drawShape(160, 50, "rgba(255, 0, 255, 0.3)")
```

